# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('dateProcess', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('account', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('totalReward', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='payout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAccountApp.User'),
        ),
        migrations.AddField(
            model_name='payment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAccountApp.User'),
        ),
    ]
