# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 17:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccountApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payout',
            name='dateProcess',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
